export const PROVIDER_DESCRIPTIONS = {
  'vm-cancun': 'Deploy to the in-browser virtual machine running the Cancun fork.',
  'vm-shanghai': 'Deploy to the in-browser virtual machine running the Shanghai fork.',
  'vm-paris': 'Deploy to the in-browser virtual machine running the Paris fork.',
  'vm-london': 'Deploy to the in-browser virtual machine running the London fork.',
  'vm-berlin': 'Deploy to the in-browser virtual machine running the Berlin fork.',
  'vm-prague': 'Deploy to the in-browser virtual machine running the Prague fork.',
  'vm-mainnet-fork': 'Deploy to a fork of the Ethereum mainnet latest block in the in-browser virtual machine.',
  'vm-sepolia-fork': 'Deploy to a fork of the Sepolia testnet latest block in the in-browser virtual machine.',
  'vm-custom-fork': 'Deploy to a fork of a custom network in the in-browser virtual machine.',
  'walletconnect': 'Deploy using WalletConnect.',
  'desktopHost': 'Deploy using web metamask.',
  'basic-http-provider': 'Deploy to a Custom local network.',
  'hardhat-provider': 'Deploy to the local Hardhat dev chain.',
  'ganache-provider': 'Deploy to the local Ganache dev chain.',
  'foundry-provider': 'Deploy to the local Foundry dev chain.',
  'injected-MetaMask': 'Deploy through the Metamask browser extension.',
  'injected-Brave Wallet': 'Deploy through the Brave Wallet extension.',
  'injected-Brave': 'Deploy through the Brave browser extension.',
  'injected-metamask-optimism': 'Deploy to Optimism through the Metamask browser extension.',
  'injected-metamask-gnosis': 'Deploy to Gnosis through the Metamask browser extension.',
  'injected-metamask-chiado': 'Deploy to Gnosis Chiado Testnet through the Metamask browser extension.',
  'injected-metamask-arbitrum': 'Deploy to Arbitrum through the Metamask browser extension.',
  'injected-metamask-sepolia': 'Deploy to the Sepolia testnet through the Metamask browser extension.',
  'injected-metamask-ephemery': 'Deploy to the Ephemery testnet through the Metamask browser extension.',
  'injected-metamask-linea': 'Deploy to Linea through the Metamask browser extension.'
}

export const PROVIDER_LOGOS = {
  'injected-metamask-optimism': ['assets/img/optimism-ethereum-op-logo.png', 'assets/img/metamask.png'],
  'injected-metamask-arbitrum': ['assets/img/arbitrum-arb-logo.png', 'assets/img/metamask.png'],
  'injected-metamask-gnosis': ['assets/img/gnosis_chain.png', 'assets/img/metamask.png'],
  'injected-metamask-chiado': ['assets/img/gnosis_chain.png', 'assets/img/metamask.png'],
  'injected-metamask-linea': ['assets/img/linea_chain.png', 'assets/img/metamask.png'],
  'injected-metamask-sepolia': ['assets/img/metamask.png'],
  'injected-metamask-ephemery': ['assets/img/metamask.png'],
  'injected-MetaMask': ['assets/img/metamask.png'],
  'injected-Brave Wallet': ['assets/img/brave.png'],
  'injected-Trust Wallet': ['assets/img/trust-wallet.png'],
  'hardhat-provider': ['assets/img/hardhat.png'],
  'walletconnect': ['assets/img/Walletconnect-logo.png'],
  'foundry-provider': ['assets/img/foundry.png']
}