import React, { useEffect, useState } from 'react'
import { Alert, Spinner, Form, Button } from 'react-bootstrap'
import { getNetworkName } from '../utils/networks'
import { ZkVerificationMethod } from '../types'

export interface ZkOnChainVerifierSelection {
  address: string;
  abi: any[];
  chainId: string | number;
  networkName?: string;
  contractName?: string;
}

export interface ZkVerificationMethodResult {
  verificationMethod: ZkVerificationMethod;
  onChainVerifier?: ZkOnChainVerifierSelection;
}

interface DeployedContractEntry {
  address: string;
  name: string;
  abi?: any[];
  contractData?: { abi?: any[] };
}

interface ZkVerificationMethodModalContentProps {
  plugin: any;
  resultRef: { current: ZkVerificationMethodResult | null };
  forceOnChain?: boolean;
}

const hasVerifyProofFunction = (abi: any[] | undefined): boolean => {
  if (!Array.isArray(abi)) return false
  return abi.some((item) => item?.type === 'function' && (item?.name === 'verifyProof' || item?.name === 'verify'))
}

const getContractAbi = (contract: DeployedContractEntry | undefined): any[] | undefined => {
  return contract?.abi || contract?.contractData?.abi
}

export function ZkVerificationMethodModalContent({ plugin, resultRef, forceOnChain }: ZkVerificationMethodModalContentProps) {
  const [method, setMethod] = useState<ZkVerificationMethod | null>(forceOnChain ? 'onchain' : null)

  // zkVerify branch state
  const [checkingApiKey, setCheckingApiKey] = useState(false)
  const [hasApiKey, setHasApiKey] = useState<boolean | null>(null)

  // on-chain branch state
  const [checkingContracts, setCheckingContracts] = useState(false)
  const [isVmEnvironment, setIsVmEnvironment] = useState(false)
  const [deployedContracts, setDeployedContracts] = useState<DeployedContractEntry[]>([])
  const [selectedAddress, setSelectedAddress] = useState('')
  const [chainId, setChainId] = useState<string | number>('unknown')

  const checkZkVerifyApiKey = async () => {
    setCheckingApiKey(true)
    try {
      const apiKey = await plugin.call('settings', 'get', 'settings/zkverify-api-key')
      setHasApiKey(!!apiKey)
    } catch (e) {
      setHasApiKey(false)
    } finally {
      setCheckingApiKey(false)
    }
  }

  const checkOnChainOptions = async () => {
    setCheckingContracts(true)
    try {
      const providerObject = await plugin.call('blockchain', 'getProviderObject')
      const providerName = providerObject?.name || ''
      const isVm = providerName.startsWith('vm')

      setIsVmEnvironment(isVm)

      if (!isVm) {
        const [contracts, network] = await Promise.all([
          plugin.call('udappDeployedContracts', 'getDeployedContracts'),
          plugin.call('network', 'detectNetwork').catch(() => null)
        ])
        console.log('contracts: ', contracts)
        setDeployedContracts(Array.isArray(contracts) ? contracts : [])
        setChainId(network?.id?.toString() || 'unknown')
      } else {
        setDeployedContracts([])
      }
    } catch (e) {
      setIsVmEnvironment(false)
      setDeployedContracts([])
    } finally {
      setCheckingContracts(false)
    }
  }

  useEffect(() => {
    if (method === 'zkverify') checkZkVerifyApiKey()
    if (method === 'onchain') checkOnChainOptions()
  }, [method])

  const openSettings = async () => {
    try {
      await plugin.call('sidePanel', 'showContent', 'settings')
    } catch (e) { /* best-effort */ }
  }

  const selectedContract = deployedContracts.find((c) => c.address === selectedAddress)

  // Keep resultRef in sync with whatever is currently a valid, ready-to-continue-with
  // selection. The caller's okFn reads this synchronously when "Continue" is clicked.
  useEffect(() => {
    if (method === 'zkverify' && hasApiKey === true) {
      resultRef.current = { verificationMethod: 'zkverify' }
      return
    }

    if (method === 'onchain' && selectedContract) {
      resultRef.current = {
        verificationMethod: 'onchain',
        onChainVerifier: {
          address: selectedContract.address,
          abi: getContractAbi(selectedContract) || [],
          chainId,
          networkName: getNetworkName(chainId),
          contractName: selectedContract.name
        }
      }
      return
    }

    resultRef.current = null
  }, [method, hasApiKey, selectedContract, chainId])

  return (
    <div data-id="zkVerificationMethodModal">
      <p className="text-muted">
        {forceOnChain
          ? 'This proving scheme only supports on-chain verification. Select your deployed verifier contract.'
          : 'How should proofs generated by your ZK DApp be verified?'}
      </p>

      {!forceOnChain && (
        <Form>
          <Form.Check
            type="radio"
            id="zk-verification-method-zkverify"
            name="zkVerificationMethod"
            label="zkVerify (off-chain relay service)"
            checked={method === 'zkverify'}
            onChange={() => setMethod('zkverify')}
            className="mb-2"
          />
          <Form.Check
            type="radio"
            id="zk-verification-method-onchain"
            name="zkVerificationMethod"
            label="On-chain (verifier contract)"
            checked={method === 'onchain'}
            onChange={() => setMethod('onchain')}
          />
        </Form>
      )}

      {method === 'zkverify' && (
        <div className="mt-3">
          {checkingApiKey && (
            <div className="d-flex align-items-center text-muted">
              <Spinner animation="border" size="sm" className="me-2" />
              Checking for a zkVerify API key...
            </div>
          )}
          {!checkingApiKey && hasApiKey === true && (
            <Alert variant="success" className="mb-0">
              zkVerify (Kurier) API key found. You're good to go.
            </Alert>
          )}
          {!checkingApiKey && hasApiKey === false && (
            <Alert variant="warning" className="mb-0">
              <div className="mb-2">
                Add your zkVerify (Kurier) API key in Settings &rarr; Connected Services before continuing.
              </div>
              <Button size="sm" variant="outline-secondary" onClick={openSettings} className="me-2">
                Open Settings
              </Button>
              <Button size="sm" variant="outline-secondary" onClick={checkZkVerifyApiKey}>
                Recheck
              </Button>
            </Alert>
          )}
        </div>
      )}

      {method === 'onchain' && (
        <div className="mt-3">
          {checkingContracts && (
            <div className="d-flex align-items-center text-muted">
              <Spinner animation="border" size="sm" className="me-2" />
              Loading deployed contracts...
            </div>
          )}
          {!checkingContracts && isVmEnvironment && (
            <Alert variant="warning" className="mb-0">
              Select a live network (not Remix VM) from the Deploy &amp; Run environment dropdown, deploy your
              verifier contract to it, then reopen this dialog.
            </Alert>
          )}
          {!checkingContracts && !isVmEnvironment && deployedContracts.length === 0 && (
            <Alert variant="warning" className="mb-0">
              No deployed contracts found on the current network. Compile and deploy your verifier contract
              (Solidity Compiler + Deploy &amp; Run) first, then reopen this dialog.
            </Alert>
          )}
          {!checkingContracts && !isVmEnvironment && deployedContracts.length > 0 && (
            <>
              <Form.Group>
                <Form.Label>Select your deployed verifier contract</Form.Label>
                <Form.Select value={selectedAddress} onChange={(e) => setSelectedAddress(e.target.value)}>
                  <option value="">-- Select a contract --</option>
                  {deployedContracts.map((contract) => (
                    <option key={contract.address} value={contract.address}>
                      {contract.name} ({contract.address})
                    </option>
                  ))}
                </Form.Select>
              </Form.Group>
              {selectedContract && !hasVerifyProofFunction(getContractAbi(selectedContract)) && (
                <Alert variant="warning" className="mt-2 mb-0">
                  This contract's ABI doesn't appear to expose a `verifyProof` function. Make sure you selected
                  the generated verifier contract.
                </Alert>
              )}
            </>
          )}
        </div>
      )}
    </div>
  )
}
