export { default as remixDefault } from './templates/remixDefault'
export { default as simpleEip7702 } from './templates/simpleEip7702'
export { default as introToEIP7702 } from './templates/introToEIP7702'
export { default as blank } from './templates/blank'
export { default as ozerc20 } from './templates/ozerc20'
export { default as ozerc721 } from './templates/ozerc721'
export { default as ozerc1155 } from './templates/ozerc1155'
export { default as zeroxErc20 } from './templates/zeroxErc20'
export { default as gnosisSafeMultisig } from './templates/gnosisSafeMultisig'
export { default as playground } from './templates/playground'
export { default as empty } from './templates/empty'
export { default as semaphore } from './templates/semaphore'
export { default as hashchecker } from './templates/hashchecker'
export { default as rln } from './templates/rln'
export { default as multNr } from './templates/multiplierNoir'
export { default as stealthDropNr } from './templates/stealthdropNoir'
export { default as rangeProofNr } from './templates/rangeProofNoir'
export { default as votingNr } from './templates/votingNoir'
export { default as recursiveNr } from './templates/recursiveNoir'
export { default as sudokuNr } from './templates/sudokuNoir'
export { default as zkKYCNr } from './templates/zkKYCNoir'
export { default as ageVerifierCircom } from './templates/ageVerifierCircom'
export { default as sudokuCircom } from './templates/sudokuCircom'
export { default as merkleProofCircom } from './templates/merkleProofCircom'
export { default as privateVotingCircom } from './templates/privateVotingCircom'
export { default as tornadoCashCircom } from './templates/tornadoCashCircom'
export { default as creAIPredictionMarket } from './templates/creAIPredictionMarket'
export { default as creWorldCupPredictionMarket } from './templates/creWorldCupPredictionMarket'

// DeFi & Advanced Templates
export { default as erc4626Vault } from './templates/erc4626Vault'
export { default as ammDex } from './templates/ammDex'
export { default as lendingProtocol } from './templates/lendingProtocol'
export { default as stablecoin } from './templates/stablecoin'
export { default as derivativesProtocol } from './templates/derivativesProtocol'
export { default as yieldAggregator } from './templates/yieldAggregator'
export { default as daoGovernance } from './templates/daoGovernance'
export { default as erc4337Account } from './templates/erc4337Account'
export { default as proxyPatterns } from './templates/proxyPatterns'
export { default as crossChainBridge } from './templates/crossChainBridge'
export { default as nftMarketplace } from './templates/nftMarketplace'
export { default as ensSystem } from './templates/ensSystem'

export { contractDeployerScripts } from './script-templates/contract-deployer'
export { etherscanScripts } from './script-templates/etherscan'
export { sindriScripts } from './script-templates/sindri'
export { contractCreate2Factory } from './script-templates/create2-solidity-factory'
export { runSolidityUnittestingAction } from './script-templates/solidity-test-action'
export { runSlitherAction } from './script-templates/slither-action'
export { runJsTestAction } from './script-templates/run-js-test-action'

