/**
 * Blockchain Events - Blockchain interactions and UDAPP tracking events
 *
 * This file contains all blockchain and universal dapp related Matomo events.
 */

import { MatomoEventBase } from '../core/base-types';

export interface BlockchainEvent extends MatomoEventBase {
  category: 'blockchain';
  action:
    | 'accountChanged'
    | 'connectionError'
    | 'transactionFailed'
    | 'providerPinned'
    | 'providerUnpinned'
    | 'deployWithProxy'
    | 'upgradeWithProxy';
}

export interface UdappEvent extends MatomoEventBase {
  category: 'udapp';
  action:
    | 'sendTransaction-from-plugin'
    | 'sendTransaction-from-gui'
    | 'safeSmartAccount'
    | 'hardhat'
    | 'sendTx'
    | 'call'
    | 'lowLevelinteractions'
    | 'transact'
    | 'syncContracts'
    | 'forkState'
    | 'deleteState'
    | 'pinContracts'
    | 'signUsingAccount'
    | 'contractDelegation'
    | 'useAtAddress'
    | 'DeployAndPublish'
    | 'DeployOnly'
    | 'DeployContractTo'
    | 'broadcastCompilationResult'
    | 'environmentDropdownOpen'
    | 'environmentSelected'
    | 'categoryDropdownOpen'
    | 'categorySelected'
    | 'accountDropdownOpen'
    | 'accountSelected'
    | 'accountAliasEditStart'
    | 'accountAliasSaved'
    | 'accountAliasCancelled'
    | 'copyAccountAddress'
    | 'copyDelegationAddress'
    | 'kebabMenuOpen'
    | 'renameAccount'
    | 'newAccount'
    | 'createSmartAccount'
    | 'authorizeDelegation'
    | 'deleteAccount'
    | 'deleteDelegation'
    | 'forkDialogOpen'
    | 'forkDialogClose'
    | 'forkNameInput'
    | 'forkSubmit'
    | 'resetDialogOpen'
    | 'resetDialogClose'
    | 'resetCancel'
    | 'resetConfirm'
    | 'signMessageInput'
    | 'signEIP712'
    | 'delegationAddressInput'
    | 'smartAccountLearnMore'
    | 'passphraseInput'
    | 'passphraseConfirmInput'
    | 'contractDropdownOpen'
    | 'contractSelected'
    | 'compileContract'
    | 'recompileContract'
    | 'contractKebabMenuOpen'
    | 'copyContractABI'
    | 'contractSaveABI'
    | 'copyContractBytecode'
    | 'deployCardToggle'
    | 'deployWithProxyToggle'
    | 'upgradeWithProxyToggle'
    | 'proxyDropdownOpen'
    | 'proxyAddressSelected'
    | 'proxyAddressInput'
    | 'proxyConstructorInput'
    | 'proxyConstructorExpand'
    | 'copyProxyInput'
    | 'verifyContractToggle'
    | 'constructorInput'
    | 'constructorExpand'
    | 'copyConstructorInput'
    | 'copyCallData'
    | 'copyParameters'
    | 'valueInput'
    | 'valueUnitChange'
    | 'gasLimitToggle'
    | 'gasLimitInput'
    | 'deployButtonClick'
    | 'mainnetMaxPriorityFeeInput'
    | 'mainnetMaxFeeInput'
    | 'mainnetGasPriceInput'
    | 'mainnetConfirmCheckbox'
    | 'copyTransactionData'
    | 'addContractButtonClick'
    | 'clearAllContractsButtonClick'
    | 'addContractDialogClose'
    | 'addContractAddressInput'
    | 'addContractSubmit'
    | 'clearAllDialogClose'
    | 'clearAllDialogCancel'
    | 'clearAllDialogConfirm'
    | 'scrollToNewInstanceClick'
    | 'pinContractToggle'
    | 'copyDeployedContractAddress'
    | 'deployedContractKebabMenuOpen'
    | 'deployedContractToggle'
    | 'highLevelInteractionToggle'
    | 'lowLevelInteractionToggle'
    | 'deployedContractFunctionSelect'
    | 'deployedContractFunctionInput'
    | 'deployedContractExecute'
    | 'deployedContractCalldataInput'
    | 'deployedContractValueInput'
    | 'deployedContractValueUnitChange'
    | 'deployedContractGasLimitToggle'
    | 'deployedContractGasLimitInput'
    | 'deployedContractTreeExpand'
    | 'deployedContractCreateDapp'
    | 'deployedContractNameENS'
    | 'deployedContractCopyABI'
    | 'deployedContractSaveABI'
    | 'deployedContractCopyBytecode'
    | 'deployedContractOpenExplorer'
    | 'deployedContractRemove'
    | 'transactionsAccordionToggle'
    | 'transactionsSaveButtonClick'
    | 'transactionsClearAllButtonClick'
    | 'transactionsSaveDialogClose'
    | 'transactionsScenarioInput'
    | 'transactionsSaveScenario'
    | 'transactionsClearAllDialogClose'
    | 'transactionsClearAllCancel'
    | 'transactionsClearAllConfirm'
    | 'transactionsTabChange'
    | 'transactionsSortChange'
    | 'transactionCopyHash'
    | 'transactionKebabMenuOpen'
    | 'transactionDebug'
    | 'transactionReplay'
    | 'transactionOpenTerminal'
    | 'transactionOpenExplorer'
    | 'transactionClear'
    | 'transactionRecordCardToggle'
    | 'transactionRecordCopyAddress';
}

export interface RunEvent extends MatomoEventBase {
  category: 'run';
  action:
    | 'recorder'
    | 'debug';
}

